# Generated by Django 3.2.6 on 2021-11-10 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='is_authenticated',
            new_name='is_authenticatedd',
        ),
    ]
